//
// Created by Maria on 18.07.2023.
//

#ifndef UNPACKING_SFGD_DEFINES_H
#define UNPACKING_SFGD_DEFINES_H

#define SFGD_SLOT 14
#define SFGD_FEB_NCHANNELS 256
#define SFGD_FEBS_NUM 280



#endif //UNPACKING_SFGD_DEFINES_H
